export const GENRES = [
    "Action",
    "Adventure",
    "Animation",
    "Biography",
    "Comedy",
    "Crime",
    "Documentary",
    "Drama",
    "Family",
    "Fantasy",
    "Film-Noir",
    "History",
    "Horror",
    "Music",
    "Musical",
    "Mystery",
    "Romance",
    "Sci-Fi",
    "Sport",
    "Thriller",
    "War",
    "Western"
] as const;

export const SPANISH_GENRES = [
    "Acción",
    "Aventura",
    "Animación",
    "Biografía",
    "Comedia",
    "Crimen",
    "Documental",
    "Drama",
    "Familia",
    "Fantasía",
    "Cine negro",
    "Historia",
    "Terror",
    "Música",
    "Musical",
    "Misterio",
    "Romance",
    "Ciencia ficción",
    "Deporte",
    "Suspenso",
    "Guerra",
    "Western"
] as const;
